name:
    mobie
channels:
    - conda-forge
dependencies:
    - bioimage-py
    - jsonschema
    - imageio
    - pandas
    - pip
    - python-elf >0.9
    - pybdv >=0.5
    - requests
    - s3fs
    - tifffile
    - zarr >=3
    - z5py >=3
